/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-02-18 20:07:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PatientInfoScreen_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>QRMD</title>\r\n");
      out.write("<script lang=\"javascript\">\r\n");
      out.write("\tfunction addRow(tableId)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar table = document.getElementById(tableId);\r\n");
      out.write("\t\tvar rowCount = table.rows.length;\r\n");
      out.write("\t\tvar row = table.insertRow(rowCount);\r\n");
      out.write("\t\tvar counts = rowCount-1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cell1 = row.insertCell(0);\r\n");
      out.write("\t\tvar firstCell = document.createElement(\"&nbsp;\");\r\n");
      out.write("\t\tcell1.appendChild(firstCell);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cell2 = row.insertCell(1);\r\n");
      out.write("\t\tcell1.appendChild(\"Allergies:\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cell3 = row.insertCell(2);\r\n");
      out.write("\t\tvar thirdCell = document.createElement(\"input\");\r\n");
      out.write("\t\tthirdCell.type = \"text\";\r\n");
      out.write("\t\tthirdCell.name = \"allergies[\" + counts \"]\";\r\n");
      out.write("\t\tcell1.appendChild(thirdCell);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cell4 = row.insertCell(3);\r\n");
      out.write("\t\tvar fourthell = document.createElement(\"&nbsp;\");\r\n");
      out.write("\t\tcell1.appendChild(fourthCell);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("            <body>\r\n");
      out.write("                <font color=\"black\" size=\"3\">\r\n");
      out.write("                    <div align=\"center\">\r\n");
      out.write("                        <h1>QRMD</h1>\r\n");
      out.write("                        <form action=\"qrmdForm\" method=\"post\">\r\n");
      out.write("                            <table style=\"background-color: royalblue\" align=\"center\" width=\"75%\" border=\"0\" cellspacing=\"0\" cellpadding=\"2\">\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td width=\"20%\">&nbsp;</td>\r\n");
      out.write("                                    <td width=\"30%\">&nbsp;</td>\r\n");
      out.write("                                    <td width=\"20%\">&nbsp;</td>\r\n");
      out.write("                                    <td width=\"30%\">&nbsp;</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"center\">First Name: </td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"firstName\"></td>\r\n");
      out.write("                                    <td align=\"center\">Last Name: </td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"lastName\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"center\">Address 1: </td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"address1\"></td>\r\n");
      out.write("                                    <td align=\"center\">Address 2: </td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"address2\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td align=\"center\">State: </td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"state\"></td>\r\n");
      out.write("                                    <td align=\"center\">Zip Code: </td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"zipCode\"></td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                \t<td>&nbsp;</td>\r\n");
      out.write("                                    <td><input type=\"submit\" name=\"submit\" value=\"Submit\" onClick=\"submit\"></td>\r\n");
      out.write("                                    <td>&nbsp;</td>\r\n");
      out.write("                                    <td>&nbsp;</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                \t<table id=\"allergiesTable\">\r\n");
      out.write("                                \t\t<tr>\r\n");
      out.write("                                \t\t\t<td>&nbsp;</td>\r\n");
      out.write("                                \t\t\t<td>Allergies:</td>\r\n");
      out.write("                                \t\t\t<td><input type=\"text\" name=\"allergies[0]\"/></td>\r\n");
      out.write("                                \t\t\t<td>&nbsp;</td>\r\n");
      out.write("                                \t</table>\r\n");
      out.write("                                \t<input type=\"button\" value=\"Add more\" onclick=\"addRow('allergiesTable')\" />\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>&nbsp;</td>\r\n");
      out.write("                                    <td>&nbsp;</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                                </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                </font>\r\n");
      out.write("            </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
